var favourite_subject = "Biology";
console.log(favourite_subject == "Biology");
var num1 = 5;
var num2 = 10;
console.log(num1 == num2);
var my_cake = "chocolate cake";
console.log(my_cake != "chocolate cake");
var wall_colour = "Blue";
console.log(wall_colour == "Blue");
var peanut = "1kg";
console.log(peanut == "1kg");
var orange_juice = "Sour";
console.log(orange_juice == "Sour");
var number1 = 45;
var number2 = 23;
console.log(number1 < number2);
var apple = "red";
console.log(apple != "red");
var myhobby = "reading books";
console.log(myhobby == "playing  football");
var plant = " green";
console.log(plant == "green");
